model:
  intent_num: 4
  intent_dim: 10
  emb_dim: 512
  latent_dim: 64

  pretrain: pretrain_3robots.pth
  obj_pretrain: null
  train: model_3robots.pth

  center_pc: True
  block_computing: True
  use_intent: True
  use_language: False