defaults:
    - language_model.yaml
    - dataset: mix_retarget_dataset.yaml
    - _self_

model:  # override model.yaml
    latent_dim: 256
    obj_pretrain: pretrain_objects_512.pth
    encoder:
        pretrain: null

dataset:  # override cmap_dataset.yaml
    batch_size: 1  # total grasps of (robot, object) combination

split_batch_size: 1  # limited by GPU memory
gpu: 0
# name: 'model_language_not_fix_initial'
# name: 'model_language_nofix_initial_larger_transformer_openad'
name: 'model_language_nofix_initial_larger_transformer_openad_openai_256'
validate_epochs:
#    - 40
#    - 30
#    - 20
#    - 10
#    - 50
   - 60
#    - 70
#    - 80
#    - 90
#    - 100
