robot_names:
  # - 'retarget_allegro'
  # - 'retarget_leaphand'
  - 'retarget_shadowhand'

debug_object_names: null  # use part of the dataset, for debug only
dataset_name: 'oakink'
complex_language_type: 'clip_512'

batch_size: 32
num_workers: 16
object_pc_type: 'random'  # 'fixed', 'random', 'partial'

ratio:
  # retarget_allegro: 4
  # retarget_leaphand: 4
  retarget_shadowhand: 5
