robot_names:
  # - 'barrett'
  # - 'allegro'
  # - 'shadowhand'
  - 'retarget_shadowhand'

debug_object_names: ['oakink+gamecontroller']  # use part of the dataset, for debug only
dataset_name: 'combine'
complex_language_type: 'openai_256'

batch_size: 8  # 1 batch_size ≈ 4 GB GPU memory during training
num_workers: 16
object_pc_type: 'random'  # 'fixed', 'random', 'partial'

ratio:
  # barrett: 3
  # allegro: 4
  # shadowhand: 8
  retarget_shadowhand: 8
