robot_names:
  - 'shadowhand'

debug_object_names: null  # use part of the dataset, for debug only
dataset_name: 'oakink'
complex_language_type: 'openai_256'

batch_size: 1  # 1 batch_size ≈ 4 GB GPU memory during training
num_workers: 16
object_pc_type: 'random'  # 'fixed', 'random', 'partial'
use_valid_data: true

ratio:
  shadowhand: 5
