robot_names:
  - 'shadowhand'

debug_object_names: 'oakink+teapot'  # use part of the dataset, for debug only
dataset_name: 'oakink'
complex_language_type: 'clip_512'

batch_size: 10  # 1 batch_size ≈ 4 GB GPU memory during training
num_workers: 16
object_pc_type: 'random'  # 'fixed', 'random', 'partial'
use_valid_data: true
use_contact_data: true

ratio:
  shadowhand: 5
