robot_names:
  # - 'barrett'
  # - 'allegro'
  # - 'shadowhand'
  - 'retarget_shadowhand'

debug_object_names: null  # use part of the dataset, for debug only
dataset_name: 'combine'

batch_size: 8  # 1 batch_size ≈ 4 GB GPU memory during training
num_workers: 16
object_pc_type: 'random'  # 'fixed', 'random', 'partial'

ratio:
  barrett: 0
  allegro: 0
  shadowhand: 0
  retarget_shadowhand: 8