model:
  emb_dim: 512
  latent_dim: 512

  pretrain: pretrain_shadow_dgcnn_acc.pth
  obj_pretrain: null
  train: model_shadow.pth

  center_pc: True
  block_computing: True
  use_intent: False
  use_language: True