model:
  emb_dim: 512
  latent_dim: 512

  pretrain: pretrain_leap.pth
  obj_pretrain: null
  train: model_3robots.pth

  center_pc: True
  block_computing: True
  use_intent: False
  use_language: True