defaults:
  - log.yaml
  - model_embed_256.yaml
  - dataset: mix_retarget_dataset.yaml
  - _self_

name: 'model_embed_256_stage_all_lr_5e-4'

seed: 42
gpu:
  # - 0
  # - 1
  # - 2
  # - 3
  # - 4
  # - 5
  - 6
  - 7

load_from_checkpoint: False
log_every_n_steps: 5

training:
  max_epochs: 200

  save_dir: '${output_dir}/state_dict'
  save_every_n_epoch: 10

  lr: 5e-4

  loss_kl: True
  loss_kl_weight: 0.001

  loss_r: True
  loss_r_weight: 1

  loss_se3: True
  loss_se3_weight: 0.01

  loss_depth: True
  loss_depth_weight: 0.1

  cross_hand: False
  cross_object: False
  only_palm: False
  two_stage: False
