defaults:
    - model_embed_256.yaml
    - dataset: mix_retarget_dataset.yaml
    - _self_

model:  # override model.yaml
    encoder:
        pretrain: null

dataset:  # override cmap_dataset.yaml
    batch_size: 1  # total grasps of (robot, object) combination

split_batch_size: 25  # limited by GPU memory
gpu: 7
name: 'model_cross_hand_nocross_object_embed_256_stage_all'
# name: 'model_retarget_cross'
validate_epochs:
#    - 40
#    - 30
#    - 20
#    - 10
#    - 50
#    - 60
#    - 70
#    - 80
#    - 90
   - 100